/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface PpMenu {
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLPpMenuElement extends Components.PpMenu, HTMLStencilElement {
    }
    var HTMLPpMenuElement: {
        prototype: HTMLPpMenuElement;
        new (): HTMLPpMenuElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "pp-menu": HTMLPpMenuElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface PpMenu {
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "pp-menu": PpMenu;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "pp-menu": LocalJSX.PpMenu & JSXBase.HTMLAttributes<HTMLPpMenuElement>;
        }
    }
}
